/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_sch_oopsla_rsa_process_ImageProcess */

#ifndef _Included_kr_ac_sch_oopsla_rsa_process_ImageProcess
#define _Included_kr_ac_sch_oopsla_rsa_process_ImageProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_sch_oopsla_rsa_process_ImageProcess
 * Method:    nativeImageProcessing
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kr_ac_sch_oopsla_rsa_process_ImageProcess_nativeImageProcessing
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
